version: "3.7"

services:
  app:
    build: .
    init: true
  nginx:
    image: nginx:1.17.9
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app